@HandleErrorsAspNetCore_HostAddress = http://localhost:5264

GET {{HandleErrorsAspNetCore_HostAddress}}/api/divide/1/2
Accept: application/json

### Success

GET {{HandleErrorsAspNetCore_HostAddress}}/api/divide/1/0
Accept: application/json

### Error

GET {{HandleErrorsAspNetCore_HostAddress}}/api/squareroot/4
Accept: application/json

### Success

GET {{HandleErrorsAspNetCore_HostAddress}}/api/squareroot/-1
Accept: application/json

### Error